name: Bug Report
description: Report a bug or unexpected behavior
title: "[BUG]: "
labels: ["bug"]
assignees: []

body:
  - type: textarea
    id: description
    attributes:
      label: Description
      description: What went wrong?
    validations:
      required: true

  - type: textarea
    id: reproduce
    attributes:
      label: Steps to Reproduce
      placeholder: |
        1. Start new game / load save
        2. Go to...
        3. Do...
        4. See error
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected vs Actual
      placeholder: |
        Expected: ...
        Actual: ...
    validations:
      required: true

  - type: dropdown
    id: component
    attributes:
      label: Component
      options:
        - Movement / Map
        - Combat
        - Dialog
        - Quests
        - Inventory
        - Save/Load
        - UI / HUD
        - Rendering
        - Other
    validations:
      required: true

  - type: textarea
    id: environment
    attributes:
      label: Browser & OS
      placeholder: "Chrome 120, Windows 11"
    validations:
      required: false

  - type: textarea
    id: console
    attributes:
      label: Console Errors
      description: Open browser DevTools (F12) and paste any errors
      render: shell
    validations:
      required: false
