name: Feature Request
description: Propose a new feature or content
title: "[FEATURE]: "
labels: ["feature-request"]
assignees: []

body:
  - type: dropdown
    id: category
    attributes:
      label: Category
      options:
        - New Map / Area
        - New Quest
        - New NPC / Enemy
        - New Items
        - Game Mechanic
        - UI / Quality of Life
        - Other
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Description
      description: What should this feature do?
    validations:
      required: true

  - type: textarea
    id: criteria
    attributes:
      label: Success Criteria
      description: How do we know it's done?
      placeholder: |
        - Player can...
        - When X happens, then Y...
    validations:
      required: true

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Any extra details, references, or ideas
    validations:
      required: false
