name: Spec Review
description: Request review for a feature specification
title: "[SPEC]: "
labels: ["spec-review"]
assignees: []

body:
  - type: input
    id: spec-id
    attributes:
      label: Spec ID
      placeholder: "FEAT-0001"
    validations:
      required: true

  - type: input
    id: spec-file
    attributes:
      label: Spec File
      placeholder: "specs/features/FEAT-0001-name.yaml"
    validations:
      required: true

  - type: textarea
    id: summary
    attributes:
      label: Summary
      description: What does this spec define?
    validations:
      required: true

  - type: textarea
    id: questions
    attributes:
      label: Open Questions
      description: Anything that needs discussion
    validations:
      required: false
